import Navebar from '@/component/navebar/Navebar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/component/footer/Footer'
import { ThemeProvider } from '../../ThemProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">


      <body className={inter.className}>
        <div className='container'> 
          <ThemeProvider>
          <Navebar/>
          {children}
          <Footer />

          </ThemeProvider>


        </div>
      </body>
    </html>
  )
}
